[package]
name = "shared-proto"
version = "0.1.0"
authors = ["Helge Hoff <helge.hoff@truelayer.com>"]
edition = "2021"
publish = false

[dependencies]
tonic-prost = "0.14"
tonic = "0.14"
prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"
